### ISSUE TITLE
Research potential cloud deploy our services between AWS, Azure & GCP

### ISSUE THREAD

**Issue by pablocom** [YoutubeToMP3Audio/youtube-downloader-core#2]
We may want to start thinking about the cloud we want to pick up to deploy our project.

**Comment by ugm2** [comment]
I only have a little bit of experience with GCP, but AWS seems the one with more maturity.

We should not only consider prices, performance and ease of use, but which one gives us the option to work free of charge, at least in the first stages. I believe GCP does give you 300$ with a new account, but that's as far as I know.

I'll update with more info when I'm done with my research

**Comment by ugm2** [comment]
I've already decided to give GCP a try. I'll send the auth to the new user I already created
